# Read CSV

In [1]:
import pandas as pd

In [102]:
file="amazonReviews.csv"

In [104]:
df.columns

Index(['id', 'name', 'asins', 'brand', 'categories', 'keys', 'manufacturer',
       'reviews.date', 'reviews.dateAdded', 'reviews.dateSeen',
       'reviews.didPurchase', 'reviews.doRecommend', 'reviews.id',
       'reviews.numHelpful', 'reviews.rating', 'reviews.sourceURLs',
       'reviews.text', 'reviews.title', 'reviews.userCity',
       'reviews.userProvince', 'reviews.username', 'review_rating'],
      dtype='object')

In [128]:
df=pd.read_csv(file)
df.head()

id                                               name  \
0  AVqkIhwDv8e3D1O-lebb  All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...   
1  AVqkIhwDv8e3D1O-lebb  All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...   
2  AVqkIhwDv8e3D1O-lebb  All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...   
3  AVqkIhwDv8e3D1O-lebb  All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...   
4  AVqkIhwDv8e3D1O-lebb  All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...   

        asins   brand                                         categories  \
0  B01AHB9CN2  Amazon  Electronics,iPad & Tablets,All Tablets,Fire Ta...   
1  B01AHB9CN2  Amazon  Electronics,iPad & Tablets,All Tablets,Fire Ta...   
2  B01AHB9CN2  Amazon  Electronics,iPad & Tablets,All Tablets,Fire Ta...   
3  B01AHB9CN2  Amazon  Electronics,iPad & Tablets,All Tablets,Fire Ta...   
4  B01AHB9CN2  Amazon  Electronics,iPad & Tablets,All Tablets,Fire Ta...   

                                                keys manufacturer  \
0  841667104676,amazon/53004484,amazon/b01ahb9cn2...       Amazon   
1  841667104676,amazon/53004484,amazon/b01ahb9cn2...       Amazon   
2  841667104676,amazon/53004484,amazon/b01ahb9cn2...       Amazon   
3  841667104676,amazon/53004484,amazon/b01ahb9cn2...       Amazon   
4  841667104676,amazon/53004484,amazon/b01ahb9cn2...       Amazon   

               reviews.date     reviews.dateAdded  \
0  2017-01-13T00:00:00.000Z  2017-07-03T23:33:15Z   
1  2017-01-13T00:00:00.000Z  2017-07-03T23:33:15Z   
2  2017-01-13T00:00:00.000Z  2017-07-03T23:33:15Z   
3  2017-01-13T00:00:00.000Z  2017-07-03T23:33:15Z   
4  2017-01-12T00:00:00.000Z  2017-07-03T23:33:15Z   

                                    reviews.dateSeen  ... reviews.doRecommend  \
0  2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z  ...                True   
1  2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z  ...                True   
2  2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z  ...                True   
3  2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z  ...                True   
4  2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z  ...                True   

  reviews.id  reviews.numHelpful  reviews.rating  \
0        NaN                 0.0             5.0   
1        NaN                 0.0             5.0   
2        NaN                 0.0             5.0   
3        NaN                 0.0             4.0   
4        NaN                 0.0             5.0   

                                  reviews.sourceURLs  \
0  http://reviews.bestbuy.com/3545/5620406/review...   
1  http://reviews.bestbuy.com/3545/5620406/review...   
2  http://reviews.bestbuy.com/3545/5620406/review...   
3  http://reviews.bestbuy.com/3545/5620406/review...   
4  http://reviews.bestbuy.com/3545/5620406/review...   

                                        reviews.text  \
0  This product so far has not disappointed. My c...   
1  great for beginner or experienced person. Boug...   
2  Inexpensive tablet for him to use and learn on...   
3  I've had my Fire HD 8 two weeks now and I love...   
4  I bought this for my grand daughter when she c...   

                             reviews.title reviews.userCity  \
0                                   Kindle              NaN   
1                                very fast              NaN   
2  Beginner tablet for our 9 year old son.              NaN   
3                                  Good!!!              NaN   
4                Fantastic Tablet for kids              NaN   

   reviews.userProvince  reviews.username  
0                   NaN           Adapter  
1                   NaN            truman  
2                   NaN             DaveZ  
3                   NaN            Shacks  
4                   NaN         explore42  

[5 rows x 21 columns]

In [129]:
review_classification=[]
for review in df["reviews.rating"]:
    if review > 3: 
        review_classification.append("POSITIVE")
    else: #review of rating 3, 2, or 1
        review_classification.append("NEGATIVE")

In [126]:
type(df["reviews.rating"][0])

numpy.float64

In [136]:
df["review_rating"]=review_classification

In [180]:
df.head()

id                                               name  \
0  AVqkIhwDv8e3D1O-lebb  All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...   
1  AVqkIhwDv8e3D1O-lebb  All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...   
2  AVqkIhwDv8e3D1O-lebb  All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...   
3  AVqkIhwDv8e3D1O-lebb  All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...   
4  AVqkIhwDv8e3D1O-lebb  All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...   

        asins   brand                                         categories  \
0  B01AHB9CN2  Amazon  Electronics,iPad & Tablets,All Tablets,Fire Ta...   
1  B01AHB9CN2  Amazon  Electronics,iPad & Tablets,All Tablets,Fire Ta...   
2  B01AHB9CN2  Amazon  Electronics,iPad & Tablets,All Tablets,Fire Ta...   
3  B01AHB9CN2  Amazon  Electronics,iPad & Tablets,All Tablets,Fire Ta...   
4  B01AHB9CN2  Amazon  Electronics,iPad & Tablets,All Tablets,Fire Ta...   

                                                keys manufacturer  \
0  841667104676,amazon/53004484,amazon/b01ahb9cn2...       Amazon   
1  841667104676,amazon/53004484,amazon/b01ahb9cn2...       Amazon   
2  841667104676,amazon/53004484,amazon/b01ahb9cn2...       Amazon   
3  841667104676,amazon/53004484,amazon/b01ahb9cn2...       Amazon   
4  841667104676,amazon/53004484,amazon/b01ahb9cn2...       Amazon   

               reviews.date     reviews.dateAdded  \
0  2017-01-13T00:00:00.000Z  2017-07-03T23:33:15Z   
1  2017-01-13T00:00:00.000Z  2017-07-03T23:33:15Z   
2  2017-01-13T00:00:00.000Z  2017-07-03T23:33:15Z   
3  2017-01-13T00:00:00.000Z  2017-07-03T23:33:15Z   
4  2017-01-12T00:00:00.000Z  2017-07-03T23:33:15Z   

                                    reviews.dateSeen  ... reviews.id  \
0  2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z  ...        NaN   
1  2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z  ...        NaN   
2  2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z  ...        NaN   
3  2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z  ...        NaN   
4  2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z  ...        NaN   

  reviews.numHelpful  reviews.rating  \
0                0.0             5.0   
1                0.0             5.0   
2                0.0             5.0   
3                0.0             4.0   
4                0.0             5.0   

                                  reviews.sourceURLs  \
0  http://reviews.bestbuy.com/3545/5620406/review...   
1  http://reviews.bestbuy.com/3545/5620406/review...   
2  http://reviews.bestbuy.com/3545/5620406/review...   
3  http://reviews.bestbuy.com/3545/5620406/review...   
4  http://reviews.bestbuy.com/3545/5620406/review...   

                                        reviews.text  \
0  This product so far has not disappointed. My c...   
1  great for beginner or experienced person. Boug...   
2  Inexpensive tablet for him to use and learn on...   
3  I've had my Fire HD 8 two weeks now and I love...   
4  I bought this for my grand daughter when she c...   

                             reviews.title reviews.userCity  \
0                                   Kindle              NaN   
1                                very fast              NaN   
2  Beginner tablet for our 9 year old son.              NaN   
3                                  Good!!!              NaN   
4                Fantastic Tablet for kids              NaN   

  reviews.userProvince  reviews.username  review_rating  
0                  NaN           Adapter       POSITIVE  
1                  NaN            truman       POSITIVE  
2                  NaN             DaveZ       POSITIVE  
3                  NaN            Shacks       POSITIVE  
4                  NaN         explore42       POSITIVE  

[5 rows x 22 columns]

In [144]:
df2=df
df2.head()
df2['review_rating'].value_counts()

POSITIVE    32316
NEGATIVE     2344
Name: review_rating, dtype: int64

In [179]:
df_negative=df2[df2['review_rating']=="NEGATIVE"]
df_negative.head()

id                                               name  \
117  AVqkIhwDv8e3D1O-lebb  All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...   
126  AVqkIhwDv8e3D1O-lebb  All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...   
169  AVqkIhwDv8e3D1O-lebb  All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...   
222  AVqkIhwDv8e3D1O-lebb  All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...   
226  AVqkIhwDv8e3D1O-lebb  All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...   

          asins   brand                                         categories  \
117  B01AHB9CN2  Amazon  Electronics,iPad & Tablets,All Tablets,Fire Ta...   
126  B01AHB9CN2  Amazon  Electronics,iPad & Tablets,All Tablets,Fire Ta...   
169  B01AHB9CN2  Amazon  Electronics,iPad & Tablets,All Tablets,Fire Ta...   
222  B01AHB9CN2  Amazon  Electronics,iPad & Tablets,All Tablets,Fire Ta...   
226  B01AHB9CN2  Amazon  Electronics,iPad & Tablets,All Tablets,Fire Ta...   

                                                  keys manufacturer  \
117  841667104676,amazon/53004484,amazon/b01ahb9cn2...       Amazon   
126  841667104676,amazon/53004484,amazon/b01ahb9cn2...       Amazon   
169  841667104676,amazon/53004484,amazon/b01ahb9cn2...       Amazon   
222  841667104676,amazon/53004484,amazon/b01ahb9cn2...       Amazon   
226  841667104676,amazon/53004484,amazon/b01ahb9cn2...       Amazon   

                 reviews.date     reviews.dateAdded  \
117  2017-01-08T00:00:00.000Z  2017-05-21T06:03:20Z   
126  2017-01-10T00:00:00.000Z  2017-05-21T06:03:08Z   
169  2016-11-25T00:00:00.000Z  2017-05-21T06:01:20Z   
222  2016-12-30T00:00:00.000Z  2017-05-21T05:59:48Z   
226  2017-01-03T00:00:00.000Z  2017-05-21T05:59:34Z   

                                      reviews.dateSeen  ... reviews.id  \
117  2017-04-30T00:45:00.000Z,2017-06-07T09:03:00.000Z  ...        NaN   
126  2017-04-30T00:45:00.000Z,2017-06-07T09:03:00.000Z  ...        NaN   
169  2017-04-30T00:44:00.000Z,2017-06-07T09:00:00.000Z  ...        NaN   
222  2017-04-30T00:43:00.000Z,2017-06-07T09:03:00.000Z  ...        NaN   
226  2017-04-30T00:43:00.000Z,2017-06-07T09:03:00.000Z  ...        NaN   

    reviews.numHelpful  reviews.rating  \
117                0.0             2.0   
126                2.0             1.0   
169                2.0             1.0   
222                0.0             3.0   
226                0.0             3.0   

                                    reviews.sourceURLs  \
117  http://reviews.bestbuy.com/3545/5620406/review...   
126  http://reviews.bestbuy.com/3545/5620406/review...   
169  http://reviews.bestbuy.com/3545/5620406/review...   
222  http://reviews.bestbuy.com/3545/5620406/review...   
226  http://reviews.bestbuy.com/3545/5620406/review...   

                                          reviews.text  \
117  Didn't have some of the features I was looking...   
126  i Bought this around black friday for $60 hopi...   
169  I bought this tablet for my 4 year old daughte...   
222  I was hoping to use Google launcher with this ...   
226  The tablet works fine. It is responsive with g...   

                          reviews.title reviews.userCity reviews.userProvince  \
117                       Wasn't for me              NaN                  NaN   
126                   TERRIBLE DONT BUY              NaN                  NaN   
169                  Ended up returning              NaN                  NaN   
222                      A cheap tablet              NaN                  NaN   
226  Works well but too tied to Amazon.              NaN                  NaN   

     reviews.username  review_rating  
117              Mark       NEGATIVE  
126           Brandon       NEGATIVE  
169            Mijenx       NEGATIVE  
222          blargh22       NEGATIVE  
226             AZ23b       NEGATIVE  

[5 rows x 22 columns]

In [153]:
df_positive=df2[df2['review_rating']=="POSITIVE"]
df_pos=df_positive.iloc[0:2343]

In [178]:
amazon= pd.concat([df_pos,df_negative])
amazon.head()

id                                               name  \
0  AVqkIhwDv8e3D1O-lebb  All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...   
1  AVqkIhwDv8e3D1O-lebb  All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...   
2  AVqkIhwDv8e3D1O-lebb  All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...   
3  AVqkIhwDv8e3D1O-lebb  All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...   
4  AVqkIhwDv8e3D1O-lebb  All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...   

        asins   brand                                         categories  \
0  B01AHB9CN2  Amazon  Electronics,iPad & Tablets,All Tablets,Fire Ta...   
1  B01AHB9CN2  Amazon  Electronics,iPad & Tablets,All Tablets,Fire Ta...   
2  B01AHB9CN2  Amazon  Electronics,iPad & Tablets,All Tablets,Fire Ta...   
3  B01AHB9CN2  Amazon  Electronics,iPad & Tablets,All Tablets,Fire Ta...   
4  B01AHB9CN2  Amazon  Electronics,iPad & Tablets,All Tablets,Fire Ta...   

                                                keys manufacturer  \
0  841667104676,amazon/53004484,amazon/b01ahb9cn2...       Amazon   
1  841667104676,amazon/53004484,amazon/b01ahb9cn2...       Amazon   
2  841667104676,amazon/53004484,amazon/b01ahb9cn2...       Amazon   
3  841667104676,amazon/53004484,amazon/b01ahb9cn2...       Amazon   
4  841667104676,amazon/53004484,amazon/b01ahb9cn2...       Amazon   

               reviews.date     reviews.dateAdded  \
0  2017-01-13T00:00:00.000Z  2017-07-03T23:33:15Z   
1  2017-01-13T00:00:00.000Z  2017-07-03T23:33:15Z   
2  2017-01-13T00:00:00.000Z  2017-07-03T23:33:15Z   
3  2017-01-13T00:00:00.000Z  2017-07-03T23:33:15Z   
4  2017-01-12T00:00:00.000Z  2017-07-03T23:33:15Z   

                                    reviews.dateSeen  ... reviews.id  \
0  2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z  ...        NaN   
1  2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z  ...        NaN   
2  2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z  ...        NaN   
3  2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z  ...        NaN   
4  2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z  ...        NaN   

  reviews.numHelpful  reviews.rating  \
0                0.0             5.0   
1                0.0             5.0   
2                0.0             5.0   
3                0.0             4.0   
4                0.0             5.0   

                                  reviews.sourceURLs  \
0  http://reviews.bestbuy.com/3545/5620406/review...   
1  http://reviews.bestbuy.com/3545/5620406/review...   
2  http://reviews.bestbuy.com/3545/5620406/review...   
3  http://reviews.bestbuy.com/3545/5620406/review...   
4  http://reviews.bestbuy.com/3545/5620406/review...   

                                        reviews.text  \
0  This product so far has not disappointed. My c...   
1  great for beginner or experienced person. Boug...   
2  Inexpensive tablet for him to use and learn on...   
3  I've had my Fire HD 8 two weeks now and I love...   
4  I bought this for my grand daughter when she c...   

                             reviews.title reviews.userCity  \
0                                   Kindle              NaN   
1                                very fast              NaN   
2  Beginner tablet for our 9 year old son.              NaN   
3                                  Good!!!              NaN   
4                Fantastic Tablet for kids              NaN   

  reviews.userProvince  reviews.username  review_rating  
0                  NaN           Adapter       POSITIVE  
1                  NaN            truman       POSITIVE  
2                  NaN             DaveZ       POSITIVE  
3                  NaN            Shacks       POSITIVE  
4                  NaN         explore42       POSITIVE  

[5 rows x 22 columns]

# Train Test Split

In [69]:
X=df['reviews.text'].values.astype('U')
y=df['review_rating']

In [157]:
X1=amazon['reviews.text'].values.astype('U')
y1=amazon['review_rating']

In [70]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [158]:
#amazon df
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.33, random_state=42)

In [45]:
print(X_test)

1763     I received this as a gift after my original Ki...
20879    Bought this for easier reading and it meets my...
26427    Alexa does all that was described. It is like ...
8344     I researched about tablets and based on my int...
34279    This is not our first Amazon Fire---we have th...
                               ...                        
11655    Bought this as a cheaper alternative for using...
24131    I would say more but I'm still learning to use...
30223    Great Roku TV; wish I had a separate remote fo...
7884     I bought this tablet for my husband for him to...
535      I went into bestbuy to purchase a replacement ...
Name: reviews.text, Length: 11438, dtype: object


In [42]:
print(X_train)

24349    Saw it at my friend's house and thought it wou...
2264     This is my second amazon fire purchase. I want...
1232     I would like to say this is my best tablet I h...
32534    This item was very easy to hook up and use. Th...
8823     "An inexpensive 'Tablet"' was the request on t...
                               ...                        
16850    grandson really enjoys this and plays with it ...
6265     This Samsung excedes our expectations. The pic...
11284    Received as Christmas gift and I love the size...
860      I traded this in after receiving a 7" at Chris...
15795    My grandson loved this. He is 4 and it was per...
Name: reviews.text, Length: 23222, dtype: object


# Pre-Processing

In [199]:
from sklearn.feature_extraction.text import CountVectorizer ,TfidfVectorizer

vectorizer= CountVectorizer()
X_train_vectors=vectorizer.fit_transform(X_train)
X_test_vectors = vectorizer.transform(X_test)

In [200]:
#amazon df
vectorizer= TfidfVectorizer()
X1_train_vectors=vectorizer.fit_transform(X1_train)
X1_test_vectors = vectorizer.transform(X1_test)

# Classifier

#### Linear SVM

In [72]:
from sklearn.svm import SVC
model = SVC(kernel='linear')
model.fit(X_train_vectors, y_train)
model.predict(X_test_vectors)

array(['POSITIVE', 'POSITIVE', 'POSITIVE', ..., 'POSITIVE', 'POSITIVE',
       'POSITIVE'], dtype=object)

In [201]:
#amazon df
model1 = SVC(kernel='linear')
model1.fit(X1_train_vectors, y1_train)
model1.predict(X1_test_vectors)

array(['POSITIVE', 'NEGATIVE', 'NEGATIVE', ..., 'POSITIVE', 'NEGATIVE',
       'NEGATIVE'], dtype=object)

#### Decision Tree

In [81]:
from sklearn.tree import DecisionTreeClassifier
model_tree = DecisionTreeClassifier()
model_tree.fit(X_train_vectors, y_train)
model_tree.predict(X_test_vectors)

array(['NEGATIVE', 'POSITIVE', 'POSITIVE', ..., 'POSITIVE', 'POSITIVE',
       'POSITIVE'], dtype=object)

In [202]:
#amazon df
model_tree1 = DecisionTreeClassifier()
model_tree1.fit(X1_train_vectors, y1_train)
model_tree1.predict(X1_test_vectors)

array(['NEGATIVE', 'NEGATIVE', 'NEGATIVE', ..., 'POSITIVE', 'POSITIVE',
       'NEGATIVE'], dtype=object)

 `Logistic Regression`

In [85]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train_vectors, y_train)
classifier.predict(X_test_vectors)

C:\Users\oddoy\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array(['POSITIVE', 'POSITIVE', 'POSITIVE', ..., 'POSITIVE', 'POSITIVE',
       'POSITIVE'], dtype=object)

In [203]:
#amazon df
classifier1 = LogisticRegression()
classifier1.fit(X1_train_vectors, y1_train)
classifier1.predict(X1_test_vectors)

C:\Users\oddoy\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array(['POSITIVE', 'NEGATIVE', 'NEGATIVE', ..., 'POSITIVE', 'NEGATIVE',
       'NEGATIVE'], dtype=object)

# Evaluation
`GridSearchCV`,`GridSearchCV`,`GridSearchCV`

In [88]:
print(f"Training Data Score for Support Vector Classifier: {model.score(X_train_vectors, y_train)}")
print(f"Testing Data Score for Support Vector Classifier: {model.score(X_test_vectors, y_test)}")

Training Data Score for Logistic Regression: 0.9785978813194385
Testing Data Score for Logistic Regression: 0.9361776534359154


In [204]:
#amazon df
print(f"Training Data Score for Support Vector Classifier: {model1.score(X1_train_vectors, y1_train)}")
print(f"Testing Data Score for Support Vector Classifier: {model1.score(X1_test_vectors, y1_test)}")

Training Data Score for Support Vector Classifier: 0.9270700636942675
Testing Data Score for Support Vector Classifier: 0.8151260504201681


In [166]:
print(f"Training Data Score for Decision Tree: {model_tree.score(X_train_vectors, y_train)}")
print(f"Testing Data Score for Decision Tree: {model_tree.score(X_test_vectors, y_test)}")

Training Data Score for Decision Tree: 1.0
Testing Data Score for Decision Tree: 0.9103864311942648


In [205]:
#amazon df
print(f"Training Data Score for Decision Tree: {model_tree1.score(X1_train_vectors, y1_train)}")
print(f"Testing Data Score for Decision Tree: {model_tree1.score(X1_test_vectors, y1_test)}")

Training Data Score for Decision Tree: 1.0
Testing Data Score for Decision Tree: 0.7013574660633484


In [169]:
print(f"Training Data Score for Logistic Regression: {classifier.score(X_train_vectors, y_train)}")
print(f"Testing Data Score for Logistic Regression: {classifier.score(X_test_vectors, y_test)}")

Training Data Score for Logistic Regression: 0.9683059168030316
Testing Data Score for Logistic Regression: 0.9404616191641896


In [206]:
#amazon df
print(f"Training Data Score for Logistic Regression: {classifier1.score(X1_train_vectors, y1_train)}")
print(f"Testing Data Score for Logistic Regression: {classifier1.score(X1_test_vectors, y1_test)}")

Training Data Score for Logistic Regression: 0.8974522292993631
Testing Data Score for Logistic Regression: 0.8228829993535876


In [171]:
from sklearn.metrics import f1_score

f1_score(y_test,model.predict(X_test_vectors), average=None, labels=["POSITIVE","NEGATIVE"])

array([0.96625682, 0.41223833])

In [207]:
#amazon df
f1_score(y1_test,model1.predict(X1_test_vectors), average=None, labels=["POSITIVE","NEGATIVE"])

array([0.81548387, 0.81476684])

In [172]:
f1_score(y_test,model_tree.predict(X_test_vectors), average=None, labels=["POSITIVE","NEGATIVE"])

array([0.95220331, 0.28371768])

In [208]:
#amazon df
f1_score(y1_test,model_tree1.predict(X1_test_vectors), average=None, labels=["POSITIVE","NEGATIVE"])

array([0.71088861, 0.69117647])

In [173]:
f1_score(y_test,classifier.predict(X_test_vectors), average=None, labels=["POSITIVE","NEGATIVE"])

array([0.96863919, 0.41343669])

In [209]:
#amazon df
f1_score(y1_test,classifier1.predict(X1_test_vectors), average=None, labels=["POSITIVE","NEGATIVE"])

array([0.82114883, 0.82458387])

In [212]:
test_set = ['i love it','bad item do not buy','best item i have ever bought. very good','fun to use','bad','great']
new_test= vectorizer.transform(test_set)
classifier1.predict(new_test)

array(['POSITIVE', 'NEGATIVE', 'POSITIVE', 'POSITIVE', 'NEGATIVE',
       'POSITIVE'], dtype=object)

# Hyperparameter Tuning
`GridSearchCV`